const topics =  [
  "budgeting",
  "savings accounts",
  "investment strategies",
  "stock market",
  "mutual funds",
  "retirement planning",
  "compound interest",
  "diversification of investments",
  "asset allocation",
  "emergency funds",
  "debt management",
  "credit scores",
  "financial education",
  "passive income",
  "financial goals",
  "financial independence",
  "real estate investments",
  "inflation",
  "financial literacy",
  "early retirement",
];
module.exports = topics;